"""Migration

Revision ID: 27c5d5fc522e
Revises: 2c03d13b09df
Create Date: 2023-03-24 22:20:04.084177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c5d5fc522e'
down_revision = '2c03d13b09df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
