"""Migration

Revision ID: 2c03d13b09df
Revises: cfc9576696b9
Create Date: 2023-03-24 21:57:12.367526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c03d13b09df'
down_revision = 'cfc9576696b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
